name: student_management_system
description: A new Flutter student management system project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  pdf: ^3.10.7
  printing: ^5.11.1
  share_plus: ^7.2.1
  file_picker: ^6.1.1
  intl: ^0.18.0 # تم التعديل هنا لتجنب خطأ الـ Conflict

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
